"""
PyInstaller 打包脚本
==================
将 IntelNexus 打包为 Windows 可分发的目录（--onedir）。

用法:
    python build_exe.py          # 默认打包
    python build_exe.py --clean  # 清理后重新打包

输出: dist/IntelNexus/ 目录（含 IntelNexus.exe）
"""

import os
import sys
import shutil
import subprocess
import argparse
from pathlib import Path

ROOT = Path(__file__).parent
DIST_DIR = ROOT / "dist"
BUILD_DIR = ROOT / "build"
SPEC_FILE = ROOT / "intelnexus.spec"

# 需要打包的数据文件（相对于项目根）
DATA_FILES = [
    # Streamlit UI 入口脚本（main.py 通过文件路径引用，PyInstaller 不会自动收集）
    ("ui.py", "."),
    # Streamlit 主题字体
    ("static/fonts", "static/fonts"),
    # PDF 导出字体
    ("intelnexus/assets/fonts", "intelnexus/assets/fonts"),
    # Streamlit 配置
    (".streamlit/config.toml", ".streamlit"),
    # 前端库
    ("lib", "lib"),
    # 预设数据
    ("presets", "presets"),
    # 默认数据文件（首次运行的初始状态）
    # 注意：data/ 目录含用户凭据（email_settings.json 等），不打包进 EXE
    # 用户需在运行后通过 UI 配置或手动创建 data/ 目录
    # ("data", "data"),  # 已注释：避免泄露敏感凭据
    # 环境变量模板
    (".env.example", "."),
]

# 运行时钩子（修复 PyInstaller 打包后的兼容性问题）
RUNTIME_HOOKS = [
    str(ROOT / "hooks" / "rthook_streamlit_metadata.py"),
]

# PyInstaller 排除的重型可选依赖（减小包体积）
EXCLUDES = [
    "torch", "torchvision", "torchaudio",
    "spacy", "spacy.lang",
    "sentence_transformers",
    "matplotlib", "matplotlib.backends",
    "IPython", "ipykernel", "jupyter",
    "pytest", "unittest",
    "tkinter",
    "numpy.tests", "pandas.tests",
]

# 必须包含的隐式导入（PyInstaller 可能漏掉）
HIDDEN_IMPORTS = [
    "streamlit",
    "streamlit.web.cli",
    "streamlit.runtime.scriptrunner",
    "streamlit.runtime.scriptrunner.magic_funcs",
    "streamlit.delta_generator",
    "streamlit.elements",
    "streamlit.elements.arrow",
    "streamlit.elements.lib",
    "click",
    "langchain",
    "langchain_core",
    "langchain_openai",
    "langchain_ollama",
    "bs4",
    "lxml",
    "lxml.etree",
    "lxml._elementpath",
    "dateutil",
    "dateutil.parser",
    "portalocker",
    "apscheduler",
    "apscheduler.schedulers",
    "apscheduler.schedulers.background",
    "reportlab",
    "reportlab.lib",
    "docx",
    "openpyxl",
    "networkx",
    "pyvis",
    "dotenv",
    "intelnexus",
    "intelnexus.core",
    "intelnexus.core.llm",
    "intelnexus.core.llm.core",
    "intelnexus.core.search",
    "intelnexus.core.search.registry",
    "intelnexus.core.search.sources",
    "intelnexus.analysis",
    "intelnexus.briefing",
    "intelnexus.config",
    "intelnexus.ui",
    "intelnexus.topics",
    "intelnexus.export",
    "intelnexus.knowledge",
]


def clean():
    """清理构建产物。"""
    for d in [DIST_DIR, BUILD_DIR]:
        if d.exists():
            print(f"Cleaning {d}...")
            shutil.rmtree(d)
    if SPEC_FILE.exists():
        SPEC_FILE.unlink()
    print("Clean done.")


def generate_spec() -> Path:
    """生成 PyInstaller spec 文件。"""
    # 构建 data_files 列表
    data_args = []
    for src, dst in DATA_FILES:
        src_path = ROOT / src
        if src_path.exists():
            data_args.append(f"(r'{src_path}', r'{dst}')")

    data_str = ",\n        ".join(data_args)

    excludes_str = ",\n        ".join(f"'{e}'" for e in EXCLUDES)
    hidden_str = ",\n        ".join(f"'{h}'" for h in HIDDEN_IMPORTS)
    hooks_str = ",\n        ".join(f"r'{h}'" for h in RUNTIME_HOOKS if os.path.exists(h))

    spec_content = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_exe.py

a = Analysis(
    [r'{ROOT / "main.py"}'],
    pathex=[r'{ROOT}'],
    binaries=[],
    datas=[
        {data_str},
    ],
    hiddenimports=[
        {hidden_str},
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[
        {hooks_str},
    ],
    excludes=[
        {excludes_str},
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='IntelNexus',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='IntelNexus',
)
"""
    SPEC_FILE.write_text(spec_content, encoding="utf-8")
    print(f"Generated spec: {SPEC_FILE}")
    return SPEC_FILE


def build(spec_file: Path):
    """运行 PyInstaller 构建。"""
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        str(spec_file),
    ]
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        print(f"ERROR: PyInstaller exited with code {result.returncode}")
        sys.exit(1)

    exe_path = DIST_DIR / "IntelNexus" / "IntelNexus.exe"
    if exe_path.exists():
        size_mb = exe_path.stat().st_size / (1024 * 1024)
        print(f"\nBuild successful!")
        print(f"Output: {exe_path}")
        print(f"Size: {size_mb:.1f} MB")
    else:
        print(f"\nWARNING: Expected output not found at {exe_path}")
        print("Check build output above for errors.")


def main():
    parser = argparse.ArgumentParser(description="Build IntelNexus EXE")
    parser.add_argument("--clean", action="store_true", help="Clean before build")
    parser.add_argument("--spec-only", action="store_true", help="Only generate spec, don't build")
    args = parser.parse_args()

    if args.clean:
        clean()

    spec_file = generate_spec()

    if args.spec_only:
        print("Spec file generated. Run without --spec-only to build.")
        return

    build(spec_file)


if __name__ == "__main__":
    main()
